### ISSUE TITLE
didShowLeft delegate called when left view not open

### ISSUE THREAD

**Issue by ccannell** [iDevelopper/PBRevealViewController#66] opened 2019-03-10 18:45 UTC
I'm able to get PBRevealViewController to call the     

`@objc func revealController(_ revealController: PBRevealViewController, didShowLeft viewController: UIViewController)`

delegate when the left view is not open (e.g. `revealController.isLeftViewOpen == false`). I'm able to trigger this using the pan gesture to open the menu. If I make a pan gesture in just the right way the delegate will be called even when the left view doesn't open. I'm using the swift branch. Thank you.

**Comment by iDevelopper** [comment] 2019-03-10 19:37
Hi,

I can't reproduce the behaviour.

Are you sure you are testing isLeftViewOpen in didShowLeft and not in WillShowLeft?

**Comment by ccannell** [comment] 2019-03-10 20:24
Positive. I’ll post some more code.

**Comment by ccannell** [comment] 2019-03-10 23:28
I'll see if I can get it down to a small example and post a full project.

**Comment by iDevelopper** [comment] 2019-03-22 17:12
Closing this issue as no feedback given.

**Closed as completed** 2019-03-22 17:12 UTC
